language: java
jdk: oraclejdk8

sudo: required

services:
- docker

before_script:
- echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin

script:
 - ./gradlew clean pushImage

notifications:
  email: false